BINS := extapp
extapp_SOURCES := Main.cc
extapp_STATICLIBS = $(PKGDIR)/lib/libext.a

EXTERNAL_STATICLIBS := libext
libext_PATH = $(PKGDIR)/lib/libext.a
libext_DIR := $(PROJECT_ROOT)/examples/external_staticlibs/lib

include ../../../Makefile.inc
